### ISSUE TITLE
Error when mapping with qtlreaper (Interval Mapping) with F2 dataset and 0 permutations

### ISSUE THREAD

**Issue by zsloan** [genenetwork/genenetwork1#15]
Using the B6D2F2 group and the trait 1436869_at_B, if I try and run Interval Mapping with 0 permutations I get the error below. While this probably isn't a huge issue since most users would just use permutations, it would also probably be pretty easy to fix (or at least avoid the bad error page).

Traceback (most recent call last):
  File "/gnshare/gn/web/webqtl/cmdLine/webqtlCmdLine.py", line 91, in ?
    page = IntervalMappingPage.IntervalMappingPage(fd)
  File "/gnshare/gn/web/webqtl/cmdLine/../intervalMapping/IntervalMappingPage.py", line 468, in **init**
    textUrl = self.writeQTL2Text(fd, filename)
  File "/gnshare/gn/web/webqtl/cmdLine/../intervalMapping/IntervalMappingPage.py", line 618, in writeQTL2Text
    fpText.write("%s\t%s\t%2.3f\t%s\t%2.3f\t%2.3f\t%2.3f\t%2.3f\n" %(qtlresult.locus.chr, \
TypeError: float argument required

**Comment by pjotrp** [comment]
gn1 is in maintenance only.
