### ISSUE TITLE
submitSingleTrait error on null input

### ISSUE THREAD

**Issue by Millak** [genenetwork/genenetwork1#62]
home -> Enter Trait Data -> scroll to bottom and press 'Sample Data'.

on gn1:
Mod_python error: "PythonHandler main"

Traceback (most recent call last):

  File "/usr/lib64/python2.4/site-packages/mod_python/apache.py", line 299, in HandlerDispatch
    result = object(req)

  File "/gnshare/gn/web/webqtl/main.py", line 100, in handler
    page = testTraitPage.testTraitPage()

  File "/gnshare/gn/web/webqtl/showTrait/testTraitPage.py", line 31, in testTraitPage
    fd = webqtlFormData()

  File "/gnshare/gn/web/webqtl/base/webqtlFormData.py", line 68, in __init__
    self.cookies = cookieData.cookieData(Cookie.get_cookies(req)) #XZ: dictionary type. To hold values transfered from mod_python Cookie.

  File "/usr/lib64/python2.4/site-packages/mod_python/Cookie.py", line 343, in get_cookies
    if not req.headers_in.has_key("cookie"):

AttributeError: 'NoneType' object has no attribute 'headers_in'

on gn1-test:

MOD_PYTHON ERROR

ProcessId:      26
Interpreter:    'GeneNetwork'

ServerName:     'gn1-test.genenetwork.org'
DocumentRoot:   '/gnu/store/1xz2df3x5x5hxwb77fchqg0vzczbrgqx-genenetwork1-0.0.0-2.acf65ac/web'

URI:            '/webqtl/main.py'
Location:       None
Directory:      '/gnu/store/1xz2df3x5x5hxwb77fchqg0vzczbrgqx-genenetwork1-0.0.0-2.acf65ac/web/webqtl/'
Filename:       '/gnu/store/1xz2df3x5x5hxwb77fchqg0vzczbrgqx-genenetwork1-0.0.0-2.acf65ac/web/webqtl/main.py'
PathInfo:       ''

Phase:          'PythonHandler'
Handler:        'main'

Traceback (most recent call last):

  File "gnu/store/yr4dn8645j0ndf3a1nx6qrkw1msxdgli-httpd-with-mod-python-2.2.34/lib/python2.4/site-packages/mod_python/importer.py", line 1537, in HandlerDispatch
    default=default_handler, arg=req, silent=hlist.silent)

  File "gnu/store/yr4dn8645j0ndf3a1nx6qrkw1msxdgli-httpd-with-mod-python-2.2.34/lib/python2.4/site-packages/mod_python/importer.py", line 1229, in _process_target
    result = _execute_target(config, req, object, arg)

  File "gnu/store/yr4dn8645j0ndf3a1nx6qrkw1msxdgli-httpd-with-mod-python-2.2.34/lib/python2.4/site-packages/mod_python/importer.py", line 1128, in _execute_target
    result = object(arg)

  File "/gnu/store/1xz2df3x5x5hxwb77fchqg0vzczbrgqx-genenetwork1-0.0.0-2.acf65ac/web/webqtl/main.py", line 100, in handler
    page = testTraitPage.testTraitPage()

  File "/gnu/store/1xz2df3x5x5hxwb77fchqg0vzczbrgqx-genenetwork1-0.0.0-2.acf65ac/web/webqtl/showTrait/testTraitPage.py", line 31, in testTraitPage
    fd = webqtlFormData()

  File "/gnu/store/1xz2df3x5x5hxwb77fchqg0vzczbrgqx-genenetwork1-0.0.0-2.acf65ac/web/webqtl/base/webqtlFormData.py", line 68, in __init__
    self.cookies = cookieData.cookieData(Cookie.get_cookies(req)) #XZ: dictionary type. To hold values transfered from mod_python Cookie.

  File "gnu/store/yr4dn8645j0ndf3a1nx6qrkw1msxdgli-httpd-with-mod-python-2.2.34/lib/python2.4/site-packages/mod_python/Cookie.py", line 376, in get_cookies
    if not req.headers_in.has_key("cookie"):

AttributeError: 'NoneType' object has no attribute 'headers_in'

MODULE CACHE DETAILS

Accessed:       Thu Sep 24 11:31:28 2020
Generation:     1

_mp_b8767ca38448fde76c82661b44344984 {
  FileName:     '/gnu/store/1xz2df3x5x5hxwb77fchqg0vzczbrgqx-genenetwork1-0.0.0-2.acf65ac/web/webqtl/main.py'
  Instance:     1
  Generation:   1
  Modified:     Thu Jan  1 00:00:01 1970
  Imported:     Wed Sep 23 08:56:00 2020
}

**Comment by pjotrp** [comment]
It is also a bug in the main/old GN1. So I feel safe to ignore it ;)
