### ISSUE TITLE
old bug showing up in gn1-new

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork1#65]
```
Traceback (most recent call last):

  File "gnu/store/qqwmxqcp4vi0m0n3c4d632lhvwgkqyvz-httpd-with-mod-python-2.2.34/lib/python2.4/site-packages/mod_python/importer.py", line 1537, in HandlerDispatch
    default=default_handler, arg=req, silent=hlist.silent)

  File "gnu/store/qqwmxqcp4vi0m0n3c4d632lhvwgkqyvz-httpd-with-mod-python-2.2.34/lib/python2.4/site-packages/mod_python/importer.py", line 1229, in _process_target
    result = _execute_target(config, req, object, arg)

  File "gnu/store/qqwmxqcp4vi0m0n3c4d632lhvwgkqyvz-httpd-with-mod-python-2.2.34/lib/python2.4/site-packages/mod_python/importer.py", line 1128, in _execute_target
    result = object(arg)

  File "/home/gn1/production/gnshare/gn/web/webqtl/main.py", line 82, in handler
    page = ShowTraitPage.ShowTraitPage(fd)

  File "/gnshare/gn/web/webqtl/showTrait/ShowTraitPage.py", line 161, in __init__
    fd.readGenotype()

  File "/home/gn1/production/gnshare/gn/web/webqtl/base/webqtlFormData.py", line 134, in readGenotype
    self.genotype_1.read(genofilelocation)

SystemError: reaper: Memory error for MAX_MARKERNAME_SIZE
```

**Comment by pjotrp** [comment]
I think @zsloan fixed this.
