### ISSUE TITLE
Can not login

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork1#66]
Perhaps related to migration.
   I cannot log in to GN1.

   http://gn1.genenetwork.org/account.html

   Should I be somewhere else?
   I am trying to add a key trait to GN and to the HRDP —the proteomic
   batch number.
   I get this charming error.
   Location = none does not sound good ;-)

```
MOD_PYTHON ERROR

ProcessId:      664
Interpreter:    'GeneNetwork'

ServerName:     '[2]gn1-new.genenetwork.org'
DocumentRoot:   '/home/gn1/production/gnshare/gn/web/'

URI:            '/webqtl/main.py'
Location:       None
Directory:      '/home/gn1/production/gnshare/gn/web/webqtl/'
Filename:       '/home/gn1/production/gnshare/gn/web/webqtl/main.py'
PathInfo:       ''

Phase:          'PythonHandler'
Handler:        'main'

Traceback (most recent call last):

  File "gnu/store/qqwmxqcp4vi0m0n3c4d632lhvwgkqyvz-httpd-with-mod-python-2.2.34/
lib/python2.4/site-packages/mod_python/importer.py", line 1537, in HandlerDispat
ch
    default=default_handler, arg=req, silent=hlist.silent)

  File "gnu/store/qqwmxqcp4vi0m0n3c4d632lhvwgkqyvz-httpd-with-mod-python-2.2.34/
lib/python2.4/site-packages/mod_python/importer.py", line 1229, in _process_targ
et
    result = _execute_target(config, req, object, arg)

  File "gnu/store/qqwmxqcp4vi0m0n3c4d632lhvwgkqyvz-httpd-with-mod-python-2.2.34/
lib/python2.4/site-packages/mod_python/importer.py", line 1128, in _execute_targ
et
    result = object(arg)

  File "/home/gn1/production/gnshare/gn/web/webqtl/main.py", line 285, in handle
r
    from user import userLogin

ImportError: cannot import name userLogin
```

**Comment by zsloan** [comment]
Yikes, I have no clue what's going on there. It obviously seems to be
something specifically related to mod_python importing user/userLogin.py,
though it's not clear from that error why it wouldn't only apply to that
one file.

My understanding of "low level" GN1 functioning is a lot weaker than GN2,
because the "guts" of GN1 were already there when I started working at
UTHSC and I only did UI stuff for it (plus the fact that GN1 code is just a
lot less easy to understand and troubleshoot).

**Comment by BonfaceKilz** [comment]
I ran into this error(when working on this):

```
  [Tue Jan 12 02:44:00 2021] [error] [client 127.0.0.1] URI: '/webqtl/main.py', referer: http://gn1-test.genenetwork.org/account.html
  [Tue Jan 12 02:44:00 2021] [error] [client 127.0.0.1] Location: '/webqtl/main.py', referer: http://gn1-test.genenetwork.org/account.html
  [Tue Jan 12 02:44:00 2021] [error] [client 127.0.0.1] Directory: None, referer: http://gn1-test.genenetwork.org/account.html
  [Tue Jan 12 02:44:00 2021] [error] [client 127.0.0.1] Filename: '/gnu/store/xfr1swpzspvlw65gjmac4f4xi752yac6-genenetwork1-0.0.0-2.acf65ac/web/webqtl/main.py', referer: http://gn1-test.genenetwork.org/account.html
  [Tue Jan 12 02:44:00 2021] [error] [client 127.0.0.1] PathInfo: '', referer: http://gn1-test.genenetwork.org/account.html
  [Tue Jan 12 02:44:00 2021] [error] [client 127.0.0.1] Traceback (most recent call last):, referer: http://gn1-test.genenetwork.org/account.html
  [Tue Jan 12 02:44:00 2021] [error] [client 127.0.0.1]   File "gnu/store/bcw4m9ch5jkdrals4akz5b8wrc3w5pcp-httpd-with-mod-python-2.2.34/lib/python2.4/site-packages/mod_python/importer.py", line 1537, in HandlerDispatch\n    default=default_handler, arg=req, silent=hlist.silent), referer: http://gn1-test.genenetwork.org/account.html
  [Tue Jan 12 02:44:00 2021] [error] [client 127.0.0.1]   File "gnu/store/bcw4m9ch5jkdrals4akz5b8wrc3w5pcp-httpd-with-mod-python-2.2.34/lib/python2.4/site-packages/mod_python/importer.py", line 1229, in _process_target\n    result = _execute_target(config, req, object, arg), referer: http://gn1-test.genenetwork.org/account.html
  [Tue Jan 12 02:44:00 2021] [error] [client 127.0.0.1]   File "gnu/store/bcw4m9ch5jkdrals4akz5b8wrc3w5pcp-httpd-with-mod-python-2.2.34/lib/python2.4/site-packages/mod_python/importer.py", line 1128, in _execute_target\n    result = object(arg), referer: http://gn1-test.genenetwork.org/account.html
  [Tue Jan 12 02:44:00 2021] [error] [client 127.0.0.1]   File "/gnu/store/xfr1swpzspvlw65gjmac4f4xi752yac6-genenetwork1-0.0.0-2.acf65ac/web/webqtl/main.py", line 290, in handler\n    from user import userLogoff, referer: http://gn1-test.genenetwork.org/account.html
  [Tue Jan 12 02:44:00 2021] [error] [client 127.0.0.1] ImportError: cannot import name userLogoff, referer: http://gn1-test.genenetwork.org/account.html
  ```
  
  And I noted: http://modpython.org/pipermail/mod_python/2006-November/022726.html which explains the whole importing issue. Beyond that, I didn't note anything else, but I'm sure it has something to do with setting some path in a way that works with modpython...
