### ISSUE TITLE
ProbesetFreeze dir error

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork1#75]
On running correlations for 

| 6468410 | Shh | sonic hedgehog; (core) | Chr4: 0.718644 | 10.144 | 12.2 | Chr3: 95.952601 | 0.218 |

in rat.

```
Population: Rat HXBBXH
Database: UT Hippocampus Affy RaEx 1.0 Exon (Jul09) RMA
Trait ID: 6468410
Gene Symbol: Shh
Location: Chr 4 @ 0.718644 Mb
```

```
Traceback (most recent call last):
  File "/gnshare/gn/web/webqtl/cmdLine/webqtlCmdLine.py", line 96, in ?
    page = CorrelationPage.CorrelationPage(fd)
  File "/home/gn1/production/gnshare/gn/web/webqtl/correlation/CorrelationPage.py", line 251, in __init__
    DirectoryList = os.listdir(webqtlConfig.TEXTDIR)  ### List of existing text files.  Used to check if a text file already exists
OSError: [Errno 2] No such file or directory: '/gnshare/gn/web/ProbeSetFreeze_DataMatrix/'
```

**Comment by pjotrp** [comment]
Mounted directory in container - this should be fixed now.
