### ISSUE TITLE
Reaper problem when drawing heatmap?

### ISSUE THREAD

**Issue by pjotrp** [genenetwork/genenetwork1#76]
When I use the Cerebellum mRNA data on GN1 and select BRCA1 items
followed by a heatmap I get the following error:

                File "/gnshare/gn/web/webqtl/cmdLine/../heatmap/Heatmap.py", line 65, in __init__
                        self.buildCanvas(colorScheme=colorScheme, targetDescriptionChecked=targetDescriptionChecked, cl
usterChecked=clusterChecked, sessionfile=sessionfile, genotype=genotype, strainlist=strainlist, ppolar=ppolar, mpolar=m
polar, traitList=traitList, traitDataList=traitDataList, userPrivilege=userPrivilege, userName=userName)
                File "/gnshare/gn/web/webqtl/cmdLine/../heatmap/Heatmap.py", line 225, in buildCanvas
                        qtlresult = genotype.regression(strains = _strains, trait = _vals)
        AttributeError: 'genotype' object has no attribute 'regression'

@zsloan , this may be due to fixing reaper in GN1. This search does work on Lily. Can you check?

**Comment by pjotrp** [comment]
still getting 

```
Traceback (most recent call last):
  File "/gnshare/gn/web/webqtl/cmdLine/webqtlCmdLine.py", line 76, in ?
    page = heatmapPage.heatmapPage(fd)
  File "/gnshare/gn/web/webqtl/cmdLine/../heatmap/heatmapPage.py", line 87, in __init__
    heatmapObject = Heatmap(fd=fd, searchResult=searchResult, colorScheme=colorScheme, userPrivilege=self.privilege, userName=self.userName)
  File "/gnshare/gn/web/webqtl/cmdLine/../heatmap/Heatmap.py", line 65, in __init__
    self.buildCanvas(colorScheme=colorScheme, targetDescriptionChecked=targetDescriptionChecked, clusterChecked=clusterChecked, sessionfile=sessionfile, genotype=genotype, strainlist=strainlist, ppolar=ppolar, mpolar=mpolar, traitList=traitList, traitDataList=traitDataList, userPrivilege=userPrivilege, userName=userName)
  File "/gnshare/gn/web/webqtl/cmdLine/../heatmap/Heatmap.py", line 225, in buildCanvas
    qtlresult = genotype.regression(strains = _strains, trait = _vals)
AttributeError: 'genotype' object has no attribute 'regression'

```

**Comment by pjotrp** [comment]
Use GN2.
